services:
    db:
        image: postgres:14.4-alpine
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: always
        networks:
            - db
        healthcheck:
            test: ["CMD", "pg_isready", "-q"]
            interval: 10s
            timeout: 1s
            retries: 3
            start_period: 5s

networks:
    db:
